# Generated by Django 5.1.7 on 2025-05-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoTravel', '0002_destinos'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='destinos/'),
        ),
    ]
