# Generated by Django 5.1.7 on 2025-05-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoTravel', '0004_comentario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentario',
            table='Comentarios',
        ),
    ]
